# Aider config file.
# https://aider.chat/docs/config/aider_conf.html
# Architect generates chatter that is more expensive. Instead, we generate carefully crafted queries.
architect: false
gitignore: false

# Models:
# Default aliases: https://aider.chat/docs/config/model-aliases.html#built-in-aliases
alias:
  - "gemini:gemini/gemini-2.5-pro-exp-03-25"
  - "gemini-pay:gemini/gemini-2.5-pro-preview-05-06"
  - "flash:gemini/gemini-2.5-flash-preview-04-17"
# thinking-tokens, reasoning-effort
# Default models: https://aider.chat/docs/config/adv-model-settings.html
# Note it already has suitable weak-model configs subordinated to the main model.
model: gemini
# editor-model: gemini
# Only available in sonnet: thinking-tokens.
auto-commits: false
auto-accept-architect: false
# Not sure: default is true.
# auto-lint: true
llm-history-file: .aider.llm-history.log
stream: false
# Just build:
test-cmd: cd ~/yatws; bazel build -c opt //yatws/...
auto-lint: false
analytics-disable: true
# Watch the AI comments:
watch-files: false
# Debugging
verbose: false
